// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai-briefing': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-briefing.post').default>>>>
    }
    '/api/ai-curate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-curate.post').default>>>>
    }
    '/api/ai-extract-articles': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-extract-articles.post').default>>>>
    }
    '/api/ai-repo-describe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-repo-describe.post').default>>>>
    }
    '/api/ai-summarize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai-summarize.post').default>>>>
    }
    '/api/discover-feed': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/discover-feed.get').default>>>>
    }
    '/api/github-trending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github-trending.get').default>>>>
    }
    '/api/jina-fetch': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/jina-fetch.get').default>>>>
    }
    '/api/rss': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rss.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nux_17253c496c01b186537912dc293b00b4/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}