// ESLint config generated by Nuxt
import { createBasicNuxtConfig } from 'nuxt-module-eslint-config/config';
export default [
...createBasicNuxtConfig(
{
  "features": {
    "setup": true
  },
  "dirs": {
    "pages": [
      "pages"
    ],
    "composables": [
      "composables",
      "utils"
    ],
    "components": [],
    "layouts": [
      "layouts"
    ],
    "plugins": [
      "plugins"
    ],
    "middleware": [
      "middleware"
    ],
    "modules": [
      "modules"
    ],
    "layers": [
      ""
    ],
    "servers": [],
    "src": "/Users/kevinyu/Desktop/NewsPixie"
  }
}
),
]
